export { AddIcon as Plus, AddIcon as PlusIcon } from '@solar-icons/react/linear/add'
export {
  AltArrowDownIcon as ChevronDown,
  AltArrowDownIcon as ChevronDownIcon,
} from '@solar-icons/react/linear/alt-arrow-down'
export { AltArrowLeftIcon as ChevronLeftIcon } from '@solar-icons/react/linear/alt-arrow-left'
export { AltArrowRightIcon as ChevronRightIcon } from '@solar-icons/react/linear/alt-arrow-right'
export {
  AltArrowUpIcon as ChevronUp,
  AltArrowUpIcon as ChevronUpIcon,
} from '@solar-icons/react/linear/alt-arrow-up'
export { ArrowLeftIcon } from '@solar-icons/react/linear/arrow-left'
export { ArrowRightIcon } from '@solar-icons/react/linear/arrow-right'
export { CalendarIcon, CalendarIcon as CalendarRange } from '@solar-icons/react/linear/calendar'
export { CalendarDateIcon as CalendarDays } from '@solar-icons/react/linear/calendar-date'
export { CheckCircleIcon as CircleCheckIcon } from '@solar-icons/react/linear/check-circle'
export { CheckIcon } from '@solar-icons/react/linear/check'
export { ClockCircleIcon as Clock } from '@solar-icons/react/linear/clock-circle'
export { CloseCircleIcon as OctagonXIcon } from '@solar-icons/react/linear/close-circle'
export { CloseIcon as XIcon } from '@solar-icons/react/linear/close'
export { CloudRainIcon as CloudRain } from '@solar-icons/react/linear/cloud-rain'
export { CupFirstIcon as Trophy } from '@solar-icons/react/linear/cup-first'
export { DangerTriangleIcon as TriangleAlertIcon } from '@solar-icons/react/linear/danger-triangle'
export { DoubleAltArrowDownIcon as ChevronsUpDownIcon } from '@solar-icons/react/linear/double-alt-arrow-down'
export { FileAudioIcon } from '@solar-icons/react/linear/file-audio'
export { FileCodeIcon } from '@solar-icons/react/linear/file-code'
export { FileCogIcon } from '@solar-icons/react/linear/file-cog'
export { FileIcon } from '@solar-icons/react/linear/file'
export { FileTextIcon } from '@solar-icons/react/linear/file-text'
export { FileVideoCameraIcon as FileVideoIcon } from '@solar-icons/react/linear/file-video-camera'
export { FileZipIcon as FileArchiveIcon } from '@solar-icons/react/linear/file-zip'
export { GlobalIcon as Globe } from '@solar-icons/react/linear/global'
export { HamburgerMenuIcon as Menu } from '@solar-icons/react/linear/hamburger-menu'
export { HomeIcon as Home } from '@solar-icons/react/linear/home'
export { InfoCircleIcon as InfoIcon } from '@solar-icons/react/linear/info-circle'
export { LoaderIcon as Loader2, LoaderIcon as Loader2Icon } from '@solar-icons/react/linear/loader'
export { LogoutIcon as LogOut } from '@solar-icons/react/linear/logout'
export {
  MagnifierIcon as Search,
  MagnifierIcon as SearchIcon,
} from '@solar-icons/react/linear/magnifier'
export { MapPointIcon as MapPin } from '@solar-icons/react/linear/map-point'
export { MenuDotsIcon as MoreHorizontalIcon } from '@solar-icons/react/linear/menu-dots'
export { MenuDotsVerticalIcon as MoreVertical } from '@solar-icons/react/linear/menu-dots-vertical'
export { MinusIcon as Minus, MinusIcon } from '@solar-icons/react/linear/minus'
export { MoonIcon as Moon } from '@solar-icons/react/linear/moon'
export { PanelLeftIcon } from '@solar-icons/react/linear/panel-left'
export { RefreshIcon as RefreshCw } from '@solar-icons/react/linear/refresh'
export { SendSquareIcon as Send } from '@solar-icons/react/linear/send-square'
export { SettingsIcon as Settings } from '@solar-icons/react/linear/settings'
export { ShieldCrossIcon as ShieldOff } from '@solar-icons/react/linear/shield-cross'
export { ShieldIcon as Shield } from '@solar-icons/react/linear/shield'
export { SunIcon as Sun } from '@solar-icons/react/linear/sun'
export { TargetIcon as Target } from '@solar-icons/react/linear/target'
export { TrashBin2Icon as Trash2 } from '@solar-icons/react/linear/trash-bin-2'
export { UserIcon as User } from '@solar-icons/react/linear/user'
export { UsersGroupRoundedIcon as UsersRound } from '@solar-icons/react/linear/users-group-rounded'
export { UsersGroupTwoRoundedIcon as Users } from '@solar-icons/react/linear/users-group-two-rounded'
export { Widget5Icon as LayoutDashboard } from '@solar-icons/react/linear/widget-5'

export type { Icon as SolarIcon } from '@solar-icons/react/lib/types'
