// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * UpdateNotificationPreferenceSchema
 */
export type UpdateNotificationPreferenceSchema = {
    emailEnabled?: boolean;
    pushEnabled?: boolean;
    notifyNewMatch?: boolean;
    notifyRsvpReminder?: boolean;
    notifyMatchCancelled?: boolean;
    notifyChatMention?: boolean;
    notifyAllChatMessages?: boolean;
};

/**
 * RegisterDeviceSchema
 */
export type RegisterDeviceSchema = {
    token: string;
    platform: 'ios' | 'android' | 'web';
};

/**
 * CreateMatchMessageSchema
 */
export type CreateMatchMessageSchema = {
    body: string;
    mentionedUserIds?: Array<string>;
};

/**
 * UpdateClubSchema
 */
export type UpdateClubSchema = {
    name?: string;
    venue?: string | null;
    sportType?: 'football' | 'futsal' | 'basketball' | 'volleyball' | 'tennis' | 'padel' | 'badminton' | 'other' | null;
    defaultMaxCapacity?: number | null;
};

/**
 * UpdateMemberRoleSchema
 */
export type UpdateMemberRoleSchema = {
    role: 'admin' | 'member';
};

/**
 * CreateMatchSchema
 */
export type CreateMatchSchema = {
    seasonId: string;
    title: string;
    startsAt: string;
    location?: string;
    maxCapacity: number;
    reminderOffsetsHours?: Array<number>;
    recurrence?: {
        frequency: 'weekly' | 'monthly' | 'monthly_nth_weekday' | 'custom';
        rrule?: string;
        endsAt?: string;
        occurrenceCount?: number;
    };
};

/**
 * UpdateMatchSchema
 */
export type UpdateMatchSchema = {
    title?: string;
    startsAt?: string;
    location?: string | null;
    maxCapacity?: number;
    blueScore?: number | null;
    redScore?: number | null;
    reminderOffsetsHours?: Array<number> | null;
};

/**
 * CancelMatchSchema
 */
export type CancelMatchSchema = {
    reason?: string;
};

/**
 * RespondAttendanceSchema
 */
export type RespondAttendanceSchema = {
    status: 'present' | 'absent';
};

/**
 * SetAttendanceSchema
 */
export type SetAttendanceSchema = {
    status: 'present' | 'absent' | 'pending';
};

/**
 * SetLineupSchema
 */
export type SetLineupSchema = {
    assignments: Array<{
        userId: string;
        team: 'blue' | 'red';
    }>;
};

/**
 * SetPlayerTeamSchema
 */
export type SetPlayerTeamSchema = {
    team: 'blue' | 'red' | null;
};

/**
 * UpsertMatchCostSchema
 */
export type UpsertMatchCostSchema = {
    pitchCostCents: number;
    extrasCostCents: number;
};

/**
 * UpdateFeeStatusSchema
 */
export type UpdateFeeStatusSchema = {
    status: 'owed' | 'paid' | 'waived';
};

/**
 * ClubPaymentLinkSchema
 */
export type ClubPaymentLinkSchema = {
    paymentLink?: string | null;
};

/**
 * CreateSeasonSchema
 */
export type CreateSeasonSchema = {
    name: string;
    startsAt: string;
    endsAt?: string;
};

/**
 * UpdateSeasonSchema
 */
export type UpdateSeasonSchema = {
    name?: string;
    startsAt?: string;
    endsAt?: string | null;
    status?: 'active' | 'closed';
};

/**
 * UpsertMatchStatsSchema
 */
export type UpsertMatchStatsSchema = {
    stats: Array<{
        userId: string;
        goals: number;
        assists: number;
    }>;
};

/**
 * NotificationPreferenceSchema
 */
export type NotificationPreferenceSchema = {
    id: string;
    emailEnabled: boolean;
    pushEnabled: boolean;
    notifyNewMatch: boolean;
    notifyRsvpReminder: boolean;
    notifyMatchCancelled: boolean;
    notifyChatMention: boolean;
    notifyAllChatMessages: boolean;
};

/**
 * MatchMessageSchema
 */
export type MatchMessageSchema = {
    id: string;
    matchId: string;
    authorId: string;
    authorName: string;
    body: string;
    mentionedUserIds: Array<string>;
    createdAt: string;
};

export type GetDefault = Array<SeasonSchema>;

/**
 * ClubSchema
 */
export type ClubSchema = {
    id: string;
    name: string;
    slug?: string | null;
    logo?: string | null;
    paymentLink?: string | null;
    venue?: string | null;
    sportType?: 'football' | 'futsal' | 'basketball' | 'volleyball' | 'tennis' | 'padel' | 'badminton' | 'other' | null;
    defaultMaxCapacity?: number | null;
    createdAt: string;
};

/**
 * ClubMemberSchema
 */
export type ClubMemberSchema = {
    id: string;
    userId: string;
    name: string;
    email: string;
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    role: 'owner' | 'admin' | 'member';
    createdAt: string;
};

export type GetOrganizationIdMembers = Array<ClubMemberSchema>;

/**
 * MatchSchema
 */
export type MatchSchema = {
    id: string;
    organizationId: string;
    seasonId: string;
    seriesId?: string | null;
    title: string;
    startsAt: string;
    location?: string | null;
    maxCapacity: number;
    status: 'scheduled' | 'cancelled' | 'played';
    blueScore?: number | null;
    redScore?: number | null;
    reminderOffsetsHours?: Array<number> | null;
    presentCount?: number;
    viewerTeam?: 'blue' | 'red' | null;
    cancellationReason?: string | null;
    createdAt: string;
};

export type PostDefault = Array<MatchSchema>;

/**
 * AttendanceSchema
 */
export type AttendanceSchema = {
    id: string;
    matchId: string;
    userId: string;
    userName: string;
    status: 'present' | 'absent' | 'pending';
    respondedAt?: string | null;
};

export type GetMatchIdAttendances = Array<AttendanceSchema>;

/**
 * LineupSchema
 */
export type LineupSchema = {
    id: string;
    matchId: string;
    userId: string;
    userName: string;
    team: 'blue' | 'red';
};

export type GetMatchIdLineups = Array<LineupSchema>;

export type PutMatchIdLineups = Array<LineupSchema>;

export type PutMatchIdLineupsUserId = Array<LineupSchema>;

/**
 * MatchCostSchema
 */
export type MatchCostSchema = {
    id: string;
    matchId: string;
    pitchCostCents: number;
    extrasCostCents: number;
    perPlayerCents?: number;
    presentCount?: number;
};

/**
 * SessionFeeSchema
 */
export type SessionFeeSchema = {
    id: string;
    matchId: string;
    userId: string;
    userName: string;
    amountCents: number;
    status: 'owed' | 'paid' | 'waived';
    paidAt?: string | null;
};

export type GetMatchesMatchIdFees = Array<SessionFeeSchema>;

/**
 * SeasonSchema
 */
export type SeasonSchema = {
    id: string;
    organizationId: string;
    name: string;
    startsAt: string;
    endsAt?: string | null;
    status: 'active' | 'closed';
    createdAt: string;
};

/**
 * MatchStatSchema
 */
export type MatchStatSchema = {
    id: string;
    matchId: string;
    userId: string;
    userName: string;
    goals: number;
    assists: number;
};

export type PutMatchesMatchIdStats = Array<MatchStatSchema>;

export type GetMatchesMatchIdStats = Array<MatchStatSchema>;

/**
 * SeasonPlayerStatSchema
 */
export type SeasonPlayerStatSchema = {
    userId: string;
    userName: string;
    goals: number;
    assists: number;
    matchesPlayed: number;
};

export type GetSeasonsSeasonIdStats = Array<SeasonPlayerStatSchema>;

/**
 * SeasonHomeStatsSchema
 */
export type SeasonHomeStatsSchema = {
    season: {
        id: string;
        name: string;
    } | null;
    club: ClubHomeStatsSchema;
    me: PersonalHomeStatsSchema;
};

/**
 * ClubHomeStatsSchema
 */
export type ClubHomeStatsSchema = {
    matchesPlayed: number;
    topScorer: {
        userId: string;
        userName: string;
        value: number;
    } | null;
    mostWins: {
        userId: string;
        userName: string;
        value: number;
    } | null;
    mostLosses: {
        userId: string;
        userName: string;
        value: number;
    } | null;
    mostPlayedTogether: {
        /**
         * PlayerRefSchema
         */
        playerA: {
            userId: string;
            userName: string;
        };
        /**
         * PlayerRefSchema
         */
        playerB: {
            userId: string;
            userName: string;
        };
        matchesTogether: number;
    } | null;
};

/**
 * PersonalHomeStatsSchema
 */
export type PersonalHomeStatsSchema = {
    matchesPlayed: number;
    goals: number;
    wins: number;
    losses: number;
};

export type ChatControllerOrganizationId = string;

export type ChatControllerMatchId = string;

export type MatchControllerOrganizationId = string;

export type PaymentControllerOrganizationId = string;

export type SeasonControllerOrganizationId = string;

export type StatsControllerOrganizationId = string;

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type ClubControllerListMineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/clubs';
};

export type ClubControllerListMineResponses = {
    /**
     * Successful response
     */
    200: GetDefault;
};

export type ClubControllerListMineResponse = ClubControllerListMineResponses[keyof ClubControllerListMineResponses];

export type ClubControllerGetOneData = {
    body?: never;
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}';
};

export type ClubControllerGetOneResponses = {
    /**
     * Successful response
     */
    200: ClubSchema;
};

export type ClubControllerGetOneResponse = ClubControllerGetOneResponses[keyof ClubControllerGetOneResponses];

export type ClubControllerUpdateData = {
    /**
     * UpdateClubSchema
     */
    body: {
        name?: string;
        venue?: string | null;
        sportType?: 'football' | 'futsal' | 'basketball' | 'volleyball' | 'tennis' | 'padel' | 'badminton' | 'other' | null;
        defaultMaxCapacity?: number | null;
    };
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}';
};

export type ClubControllerUpdateResponses = {
    /**
     * Successful response
     */
    200: ClubSchema;
};

export type ClubControllerUpdateResponse = ClubControllerUpdateResponses[keyof ClubControllerUpdateResponses];

export type ClubControllerListMembersData = {
    body?: never;
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/members';
};

export type ClubControllerListMembersResponses = {
    /**
     * Successful response
     */
    200: GetOrganizationIdMembers;
};

export type ClubControllerListMembersResponse = ClubControllerListMembersResponses[keyof ClubControllerListMembersResponses];

export type ClubControllerUpdateRoleData = {
    /**
     * UpdateMemberRoleSchema
     */
    body: {
        role: 'admin' | 'member';
    };
    path: {
        memberId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/members/{memberId}/role';
};

export type ClubControllerUpdateRoleResponses = {
    /**
     * Successful response
     */
    200: ClubMemberSchema;
};

export type ClubControllerUpdateRoleResponse = ClubControllerUpdateRoleResponses[keyof ClubControllerUpdateRoleResponses];

export type SeasonControllerListData = {
    body?: never;
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/seasons';
};

export type SeasonControllerListResponses = {
    /**
     * Successful response
     */
    200: GetDefault;
};

export type SeasonControllerListResponse = SeasonControllerListResponses[keyof SeasonControllerListResponses];

export type SeasonControllerCreateData = {
    /**
     * CreateSeasonSchema
     */
    body: {
        name: string;
        startsAt: string;
        endsAt?: string;
    };
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/seasons';
};

export type SeasonControllerCreateResponses = {
    /**
     * Successful response
     */
    200: SeasonSchema;
};

export type SeasonControllerCreateResponse = SeasonControllerCreateResponses[keyof SeasonControllerCreateResponses];

export type SeasonControllerGetData = {
    body?: never;
    path: {
        seasonId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/seasons/{seasonId}';
};

export type SeasonControllerGetResponses = {
    /**
     * Successful response
     */
    200: SeasonSchema;
};

export type SeasonControllerGetResponse = SeasonControllerGetResponses[keyof SeasonControllerGetResponses];

export type SeasonControllerUpdateData = {
    /**
     * UpdateSeasonSchema
     */
    body: {
        name?: string;
        startsAt?: string;
        endsAt?: string | null;
        status?: 'active' | 'closed';
    };
    path: {
        seasonId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/seasons/{seasonId}';
};

export type SeasonControllerUpdateResponses = {
    /**
     * Successful response
     */
    200: SeasonSchema;
};

export type SeasonControllerUpdateResponse = SeasonControllerUpdateResponses[keyof SeasonControllerUpdateResponses];

export type MatchControllerListData = {
    body?: never;
    path: {
        organizationId: string;
    };
    query: {
        seasonId: string;
    };
    url: '/api/clubs/{organizationId}/matches';
};

export type MatchControllerListResponses = {
    /**
     * Successful response
     */
    200: GetDefault;
};

export type MatchControllerListResponse = MatchControllerListResponses[keyof MatchControllerListResponses];

export type MatchControllerCreateData = {
    /**
     * CreateMatchSchema
     */
    body: {
        seasonId: string;
        title: string;
        startsAt: string;
        location?: string;
        maxCapacity: number;
        reminderOffsetsHours?: Array<number>;
        recurrence?: {
            frequency: 'weekly' | 'monthly' | 'monthly_nth_weekday' | 'custom';
            rrule?: string;
            endsAt?: string;
            occurrenceCount?: number;
        };
    };
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches';
};

export type MatchControllerCreateResponses = {
    /**
     * Successful response
     */
    200: PostDefault;
};

export type MatchControllerCreateResponse = MatchControllerCreateResponses[keyof MatchControllerCreateResponses];

export type MatchControllerGetData = {
    body?: never;
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}';
};

export type MatchControllerGetResponses = {
    /**
     * Successful response
     */
    200: MatchSchema;
};

export type MatchControllerGetResponse = MatchControllerGetResponses[keyof MatchControllerGetResponses];

export type MatchControllerUpdateData = {
    /**
     * UpdateMatchSchema
     */
    body: {
        title?: string;
        startsAt?: string;
        location?: string | null;
        maxCapacity?: number;
        blueScore?: number | null;
        redScore?: number | null;
        reminderOffsetsHours?: Array<number> | null;
    };
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}';
};

export type MatchControllerUpdateResponses = {
    /**
     * Successful response
     */
    200: MatchSchema;
};

export type MatchControllerUpdateResponse = MatchControllerUpdateResponses[keyof MatchControllerUpdateResponses];

export type MatchControllerCancelData = {
    /**
     * CancelMatchSchema
     */
    body: {
        reason?: string;
    };
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/cancel';
};

export type MatchControllerCancelResponses = {
    /**
     * Successful response
     */
    200: MatchSchema;
};

export type MatchControllerCancelResponse = MatchControllerCancelResponses[keyof MatchControllerCancelResponses];

export type MatchControllerMarkPlayedData = {
    body?: never;
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/played';
};

export type MatchControllerMarkPlayedResponses = {
    /**
     * Successful response
     */
    200: MatchSchema;
};

export type MatchControllerMarkPlayedResponse = MatchControllerMarkPlayedResponses[keyof MatchControllerMarkPlayedResponses];

export type MatchControllerListAttendancesData = {
    body?: never;
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/attendances';
};

export type MatchControllerListAttendancesResponses = {
    /**
     * Successful response
     */
    200: GetMatchIdAttendances;
};

export type MatchControllerListAttendancesResponse = MatchControllerListAttendancesResponses[keyof MatchControllerListAttendancesResponses];

export type MatchControllerRespondData = {
    /**
     * RespondAttendanceSchema
     */
    body: {
        status: 'present' | 'absent';
    };
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/attendances/me';
};

export type MatchControllerRespondResponses = {
    /**
     * Successful response
     */
    200: AttendanceSchema;
};

export type MatchControllerRespondResponse = MatchControllerRespondResponses[keyof MatchControllerRespondResponses];

export type MatchControllerSetAttendanceData = {
    /**
     * SetAttendanceSchema
     */
    body: {
        status: 'present' | 'absent' | 'pending';
    };
    path: {
        userId: string;
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/attendances/{userId}';
};

export type MatchControllerSetAttendanceResponses = {
    /**
     * Successful response
     */
    200: AttendanceSchema;
};

export type MatchControllerSetAttendanceResponse = MatchControllerSetAttendanceResponses[keyof MatchControllerSetAttendanceResponses];

export type MatchControllerListLineupsData = {
    body?: never;
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/lineups';
};

export type MatchControllerListLineupsResponses = {
    /**
     * Successful response
     */
    200: GetMatchIdLineups;
};

export type MatchControllerListLineupsResponse = MatchControllerListLineupsResponses[keyof MatchControllerListLineupsResponses];

export type MatchControllerSetLineupData = {
    /**
     * SetLineupSchema
     */
    body: {
        assignments: Array<{
            userId: string;
            team: 'blue' | 'red';
        }>;
    };
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/lineups';
};

export type MatchControllerSetLineupResponses = {
    /**
     * Successful response
     */
    200: PutMatchIdLineups;
};

export type MatchControllerSetLineupResponse = MatchControllerSetLineupResponses[keyof MatchControllerSetLineupResponses];

export type MatchControllerSetPlayerTeamData = {
    /**
     * SetPlayerTeamSchema
     */
    body: {
        team: 'blue' | 'red' | null;
    };
    path: {
        userId: string;
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/lineups/{userId}';
};

export type MatchControllerSetPlayerTeamResponses = {
    /**
     * Successful response
     */
    200: PutMatchIdLineupsUserId;
};

export type MatchControllerSetPlayerTeamResponse = MatchControllerSetPlayerTeamResponses[keyof MatchControllerSetPlayerTeamResponses];

export type NotificationControllerGetPreferencesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/preferences';
};

export type NotificationControllerGetPreferencesResponses = {
    /**
     * Successful response
     */
    200: NotificationPreferenceSchema;
};

export type NotificationControllerGetPreferencesResponse = NotificationControllerGetPreferencesResponses[keyof NotificationControllerGetPreferencesResponses];

export type NotificationControllerUpdatePreferencesData = {
    /**
     * UpdateNotificationPreferenceSchema
     */
    body: {
        emailEnabled?: boolean;
        pushEnabled?: boolean;
        notifyNewMatch?: boolean;
        notifyRsvpReminder?: boolean;
        notifyMatchCancelled?: boolean;
        notifyChatMention?: boolean;
        notifyAllChatMessages?: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/notifications/preferences';
};

export type NotificationControllerUpdatePreferencesResponses = {
    /**
     * Successful response
     */
    200: NotificationPreferenceSchema;
};

export type NotificationControllerUpdatePreferencesResponse = NotificationControllerUpdatePreferencesResponses[keyof NotificationControllerUpdatePreferencesResponses];

export type NotificationControllerRegisterDeviceData = {
    /**
     * RegisterDeviceSchema
     */
    body: {
        token: string;
        platform: 'ios' | 'android' | 'web';
    };
    path?: never;
    query?: never;
    url: '/api/notifications/devices';
};

export type NotificationControllerRegisterDeviceResponses = {
    201: unknown;
};

export type StatsControllerListMatchData = {
    body?: never;
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/stats';
};

export type StatsControllerListMatchResponses = {
    /**
     * Successful response
     */
    200: GetMatchesMatchIdStats;
};

export type StatsControllerListMatchResponse = StatsControllerListMatchResponses[keyof StatsControllerListMatchResponses];

export type StatsControllerUpsertData = {
    /**
     * UpsertMatchStatsSchema
     */
    body: {
        stats: Array<{
            userId: string;
            goals: number;
            assists: number;
        }>;
    };
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/stats';
};

export type StatsControllerUpsertResponses = {
    /**
     * Successful response
     */
    200: PutMatchesMatchIdStats;
};

export type StatsControllerUpsertResponse = StatsControllerUpsertResponses[keyof StatsControllerUpsertResponses];

export type StatsControllerSeasonStatsData = {
    body?: never;
    path: {
        seasonId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/seasons/{seasonId}/stats';
};

export type StatsControllerSeasonStatsResponses = {
    /**
     * Successful response
     */
    200: GetSeasonsSeasonIdStats;
};

export type StatsControllerSeasonStatsResponse = StatsControllerSeasonStatsResponses[keyof StatsControllerSeasonStatsResponses];

export type StatsControllerHomeStatsData = {
    body?: never;
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/home-stats';
};

export type StatsControllerHomeStatsResponses = {
    /**
     * Successful response
     */
    200: SeasonHomeStatsSchema;
};

export type StatsControllerHomeStatsResponse = StatsControllerHomeStatsResponses[keyof StatsControllerHomeStatsResponses];

export type ChatControllerListData = {
    body?: never;
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/messages';
};

export type ChatControllerListResponses = {
    /**
     * Successful response
     */
    200: GetDefault;
};

export type ChatControllerListResponse = ChatControllerListResponses[keyof ChatControllerListResponses];

export type ChatControllerPostData = {
    /**
     * CreateMatchMessageSchema
     */
    body: {
        body: string;
        mentionedUserIds?: Array<string>;
    };
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/messages';
};

export type ChatControllerPostResponses = {
    /**
     * Successful response
     */
    200: MatchMessageSchema;
};

export type ChatControllerPostResponse = ChatControllerPostResponses[keyof ChatControllerPostResponses];

export type PaymentControllerGetCostData = {
    body?: never;
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/cost';
};

export type PaymentControllerGetCostResponses = {
    /**
     * Successful response
     */
    200: MatchCostSchema;
};

export type PaymentControllerGetCostResponse = PaymentControllerGetCostResponses[keyof PaymentControllerGetCostResponses];

export type PaymentControllerUpsertCostData = {
    /**
     * UpsertMatchCostSchema
     */
    body: {
        pitchCostCents: number;
        extrasCostCents: number;
    };
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/cost';
};

export type PaymentControllerUpsertCostResponses = {
    /**
     * Successful response
     */
    200: MatchCostSchema;
};

export type PaymentControllerUpsertCostResponse = PaymentControllerUpsertCostResponses[keyof PaymentControllerUpsertCostResponses];

export type PaymentControllerListFeesData = {
    body?: never;
    path: {
        matchId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/matches/{matchId}/fees';
};

export type PaymentControllerListFeesResponses = {
    /**
     * Successful response
     */
    200: GetMatchesMatchIdFees;
};

export type PaymentControllerListFeesResponse = PaymentControllerListFeesResponses[keyof PaymentControllerListFeesResponses];

export type PaymentControllerUpdateFeeData = {
    /**
     * UpdateFeeStatusSchema
     */
    body: {
        status: 'owed' | 'paid' | 'waived';
    };
    path: {
        feeId: string;
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/fees/{feeId}';
};

export type PaymentControllerUpdateFeeResponses = {
    /**
     * Successful response
     */
    200: SessionFeeSchema;
};

export type PaymentControllerUpdateFeeResponse = PaymentControllerUpdateFeeResponses[keyof PaymentControllerUpdateFeeResponses];

export type PaymentControllerGetPaymentLinkData = {
    body?: never;
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/payment-link';
};

export type PaymentControllerGetPaymentLinkResponses = {
    /**
     * Successful response
     */
    200: ClubPaymentLinkSchema;
};

export type PaymentControllerGetPaymentLinkResponse = PaymentControllerGetPaymentLinkResponses[keyof PaymentControllerGetPaymentLinkResponses];

export type PaymentControllerSetPaymentLinkData = {
    /**
     * ClubPaymentLinkSchema
     */
    body: {
        paymentLink?: string | null;
    };
    path: {
        organizationId: string;
    };
    query?: never;
    url: '/api/clubs/{organizationId}/payment-link';
};

export type PaymentControllerSetPaymentLinkResponses = {
    /**
     * Successful response
     */
    200: ClubPaymentLinkSchema;
};

export type PaymentControllerSetPaymentLinkResponse = PaymentControllerSetPaymentLinkResponses[keyof PaymentControllerSetPaymentLinkResponses];
