// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * UpdateNotificationPreferenceSchema
 */
export const zUpdateNotificationPreferenceSchema = z.object({
    emailEnabled: z.optional(z.boolean()),
    pushEnabled: z.optional(z.boolean()),
    notifyNewMatch: z.optional(z.boolean()),
    notifyRsvpReminder: z.optional(z.boolean()),
    notifyMatchCancelled: z.optional(z.boolean()),
    notifyChatMention: z.optional(z.boolean()),
    notifyAllChatMessages: z.optional(z.boolean())
});

/**
 * RegisterDeviceSchema
 */
export const zRegisterDeviceSchema = z.object({
    token: z.string().min(1),
    platform: z.enum([
        'ios',
        'android',
        'web'
    ])
});

/**
 * CreateMatchMessageSchema
 */
export const zCreateMatchMessageSchema = z.object({
    body: z.string().min(1).max(4000),
    mentionedUserIds: z.optional(z.array(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)))
});

/**
 * UpdateClubSchema
 */
export const zUpdateClubSchema = z.object({
    name: z.optional(z.string().min(1)),
    venue: z.optional(z.union([
        z.string().min(1),
        z.null()
    ])),
    sportType: z.optional(z.union([
        z.enum([
            'football',
            'futsal',
            'basketball',
            'volleyball',
            'tennis',
            'padel',
            'badminton',
            'other'
        ]),
        z.null()
    ])),
    defaultMaxCapacity: z.optional(z.union([
        z.int().gt(0).lte(9007199254740991),
        z.null()
    ]))
});

/**
 * UpdateMemberRoleSchema
 */
export const zUpdateMemberRoleSchema = z.object({
    role: z.enum(['admin', 'member'])
});

/**
 * CreateMatchSchema
 */
export const zCreateMatchSchema = z.object({
    seasonId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    title: z.string().min(1),
    startsAt: z.string(),
    location: z.optional(z.string()),
    maxCapacity: z.int().gt(0).lte(9007199254740991),
    reminderOffsetsHours: z.optional(z.array(z.int().gt(0).lte(9007199254740991))),
    recurrence: z.optional(z.object({
        frequency: z.enum([
            'weekly',
            'monthly',
            'monthly_nth_weekday',
            'custom'
        ]),
        rrule: z.optional(z.string()),
        endsAt: z.optional(z.string()),
        occurrenceCount: z.optional(z.int().gt(0).lte(52))
    }))
});

/**
 * UpdateMatchSchema
 */
export const zUpdateMatchSchema = z.object({
    title: z.optional(z.string().min(1)),
    startsAt: z.optional(z.string()),
    location: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    maxCapacity: z.optional(z.int().gt(0).lte(9007199254740991)),
    blueScore: z.optional(z.union([
        z.int().gte(0).lte(9007199254740991),
        z.null()
    ])),
    redScore: z.optional(z.union([
        z.int().gte(0).lte(9007199254740991),
        z.null()
    ])),
    reminderOffsetsHours: z.optional(z.union([
        z.array(z.int().gt(0).lte(9007199254740991)),
        z.null()
    ]))
});

/**
 * CancelMatchSchema
 */
export const zCancelMatchSchema = z.object({
    reason: z.optional(z.string())
});

/**
 * RespondAttendanceSchema
 */
export const zRespondAttendanceSchema = z.object({
    status: z.enum(['present', 'absent'])
});

/**
 * SetAttendanceSchema
 */
export const zSetAttendanceSchema = z.object({
    status: z.enum([
        'present',
        'absent',
        'pending'
    ])
});

/**
 * SetLineupSchema
 */
export const zSetLineupSchema = z.object({
    assignments: z.array(z.object({
        userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        team: z.enum(['blue', 'red'])
    }))
});

/**
 * SetPlayerTeamSchema
 */
export const zSetPlayerTeamSchema = z.object({
    team: z.union([
        z.enum(['blue', 'red']),
        z.null()
    ])
});

/**
 * UpsertMatchCostSchema
 */
export const zUpsertMatchCostSchema = z.object({
    pitchCostCents: z.int().gte(0).lte(9007199254740991),
    extrasCostCents: z.int().gte(0).lte(9007199254740991).default(0)
});

/**
 * UpdateFeeStatusSchema
 */
export const zUpdateFeeStatusSchema = z.object({
    status: z.enum([
        'owed',
        'paid',
        'waived'
    ])
});

/**
 * ClubPaymentLinkSchema
 */
export const zClubPaymentLinkSchema = z.object({
    paymentLink: z.optional(z.union([
        z.url(),
        z.null()
    ]))
});

/**
 * CreateSeasonSchema
 */
export const zCreateSeasonSchema = z.object({
    name: z.string().min(1),
    startsAt: z.string(),
    endsAt: z.optional(z.string())
});

/**
 * UpdateSeasonSchema
 */
export const zUpdateSeasonSchema = z.object({
    name: z.optional(z.string().min(1)),
    startsAt: z.optional(z.string()),
    endsAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: z.optional(z.enum(['active', 'closed']))
});

/**
 * UpsertMatchStatsSchema
 */
export const zUpsertMatchStatsSchema = z.object({
    stats: z.array(z.object({
        userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        goals: z.int().gte(0).lte(9007199254740991),
        assists: z.int().gte(0).lte(9007199254740991)
    }))
});

/**
 * NotificationPreferenceSchema
 */
export const zNotificationPreferenceSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    emailEnabled: z.boolean(),
    pushEnabled: z.boolean(),
    notifyNewMatch: z.boolean(),
    notifyRsvpReminder: z.boolean(),
    notifyMatchCancelled: z.boolean(),
    notifyChatMention: z.boolean(),
    notifyAllChatMessages: z.boolean()
});

/**
 * MatchMessageSchema
 */
export const zMatchMessageSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    authorId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    authorName: z.string(),
    body: z.string(),
    mentionedUserIds: z.array(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)),
    createdAt: z.string()
});

/**
 * ClubSchema
 */
export const zClubSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    slug: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    logo: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    paymentLink: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    venue: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    sportType: z.optional(z.union([
        z.enum([
            'football',
            'futsal',
            'basketball',
            'volleyball',
            'tennis',
            'padel',
            'badminton',
            'other'
        ]),
        z.null()
    ])),
    defaultMaxCapacity: z.optional(z.union([
        z.int().gt(0).lte(9007199254740991),
        z.null()
    ])),
    createdAt: z.string()
});

/**
 * ClubMemberSchema
 */
export const zClubMemberSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
    firstName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    lastName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    role: z.enum([
        'owner',
        'admin',
        'member'
    ]),
    createdAt: z.string()
});

export const zGetOrganizationIdMembers = z.array(zClubMemberSchema);

/**
 * MatchSchema
 */
export const zMatchSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    seasonId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    seriesId: z.optional(z.union([
        z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        z.null()
    ])),
    title: z.string(),
    startsAt: z.string(),
    location: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    maxCapacity: z.int().gt(0).lte(9007199254740991),
    status: z.enum([
        'scheduled',
        'cancelled',
        'played'
    ]),
    blueScore: z.optional(z.union([
        z.int().gte(0).lte(9007199254740991),
        z.null()
    ])),
    redScore: z.optional(z.union([
        z.int().gte(0).lte(9007199254740991),
        z.null()
    ])),
    reminderOffsetsHours: z.optional(z.union([
        z.array(z.int().gt(0).lte(9007199254740991)),
        z.null()
    ])),
    presentCount: z.optional(z.int().gte(-9007199254740991).lte(9007199254740991)),
    viewerTeam: z.optional(z.union([
        z.enum(['blue', 'red']),
        z.null()
    ])),
    cancellationReason: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    createdAt: z.string()
});

export const zPostDefault = z.array(zMatchSchema);

/**
 * AttendanceSchema
 */
export const zAttendanceSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    userName: z.string(),
    status: z.enum([
        'present',
        'absent',
        'pending'
    ]),
    respondedAt: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zGetMatchIdAttendances = z.array(zAttendanceSchema);

/**
 * LineupSchema
 */
export const zLineupSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    userName: z.string(),
    team: z.enum(['blue', 'red'])
});

export const zGetMatchIdLineups = z.array(zLineupSchema);

export const zPutMatchIdLineups = z.array(zLineupSchema);

export const zPutMatchIdLineupsUserId = z.array(zLineupSchema);

/**
 * MatchCostSchema
 */
export const zMatchCostSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    pitchCostCents: z.int().gte(0).lte(9007199254740991),
    extrasCostCents: z.int().gte(0).lte(9007199254740991),
    perPlayerCents: z.optional(z.int().gte(0).lte(9007199254740991)),
    presentCount: z.optional(z.int().gte(-9007199254740991).lte(9007199254740991))
});

/**
 * SessionFeeSchema
 */
export const zSessionFeeSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    userName: z.string(),
    amountCents: z.int().gte(-9007199254740991).lte(9007199254740991),
    status: z.enum([
        'owed',
        'paid',
        'waived'
    ]),
    paidAt: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zGetMatchesMatchIdFees = z.array(zSessionFeeSchema);

/**
 * SeasonSchema
 */
export const zSeasonSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    startsAt: z.string(),
    endsAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: z.enum(['active', 'closed']),
    createdAt: z.string()
});

export const zGetDefault = z.array(zSeasonSchema);

/**
 * MatchStatSchema
 */
export const zMatchStatSchema = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    userName: z.string(),
    goals: z.int().gte(0).lte(9007199254740991),
    assists: z.int().gte(0).lte(9007199254740991)
});

export const zPutMatchesMatchIdStats = z.array(zMatchStatSchema);

export const zGetMatchesMatchIdStats = z.array(zMatchStatSchema);

/**
 * SeasonPlayerStatSchema
 */
export const zSeasonPlayerStatSchema = z.object({
    userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    userName: z.string(),
    goals: z.int().gte(-9007199254740991).lte(9007199254740991),
    assists: z.int().gte(-9007199254740991).lte(9007199254740991),
    matchesPlayed: z.int().gte(-9007199254740991).lte(9007199254740991)
});

export const zGetSeasonsSeasonIdStats = z.array(zSeasonPlayerStatSchema);

/**
 * ClubHomeStatsSchema
 */
export const zClubHomeStatsSchema = z.object({
    matchesPlayed: z.int().gte(0).lte(9007199254740991),
    topScorer: z.union([
        z.object({
            userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            userName: z.string(),
            value: z.int().gte(0).lte(9007199254740991)
        }),
        z.null()
    ]),
    mostWins: z.union([
        z.object({
            userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            userName: z.string(),
            value: z.int().gte(0).lte(9007199254740991)
        }),
        z.null()
    ]),
    mostLosses: z.union([
        z.object({
            userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            userName: z.string(),
            value: z.int().gte(0).lte(9007199254740991)
        }),
        z.null()
    ]),
    mostPlayedTogether: z.union([
        z.object({
            playerA: z.object({
                userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
                userName: z.string()
            }),
            playerB: z.object({
                userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
                userName: z.string()
            }),
            matchesTogether: z.int().gte(0).lte(9007199254740991)
        }),
        z.null()
    ])
});

/**
 * PersonalHomeStatsSchema
 */
export const zPersonalHomeStatsSchema = z.object({
    matchesPlayed: z.int().gte(0).lte(9007199254740991),
    goals: z.int().gte(0).lte(9007199254740991),
    wins: z.int().gte(0).lte(9007199254740991),
    losses: z.int().gte(0).lte(9007199254740991)
});

/**
 * SeasonHomeStatsSchema
 */
export const zSeasonHomeStatsSchema = z.object({
    season: z.union([
        z.object({
            id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            name: z.string()
        }),
        z.null()
    ]),
    club: zClubHomeStatsSchema,
    me: zPersonalHomeStatsSchema
});

export const zChatControllerOrganizationId = z.string();

export const zChatControllerMatchId = z.string();

export const zMatchControllerOrganizationId = z.string();

export const zPaymentControllerOrganizationId = z.string();

export const zSeasonControllerOrganizationId = z.string();

export const zStatsControllerOrganizationId = z.string();

export const zAppControllerGetHelloData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zClubControllerListMineData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zClubControllerListMineResponse = zGetDefault;

export const zClubControllerGetOneData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zClubControllerGetOneResponse = zClubSchema;

export const zClubControllerUpdateData = z.object({
    body: z.object({
        name: z.optional(z.string().min(1)),
        venue: z.optional(z.union([
            z.string().min(1),
            z.null()
        ])),
        sportType: z.optional(z.union([
            z.enum([
                'football',
                'futsal',
                'basketball',
                'volleyball',
                'tennis',
                'padel',
                'badminton',
                'other'
            ]),
            z.null()
        ])),
        defaultMaxCapacity: z.optional(z.union([
            z.int().gt(0).lte(9007199254740991),
            z.null()
        ]))
    }),
    path: z.object({
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zClubControllerUpdateResponse = zClubSchema;

export const zClubControllerListMembersData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zClubControllerListMembersResponse = zGetOrganizationIdMembers;

export const zClubControllerUpdateRoleData = z.object({
    body: z.object({
        role: z.enum(['admin', 'member'])
    }),
    path: z.object({
        memberId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zClubControllerUpdateRoleResponse = zClubMemberSchema;

export const zSeasonControllerListData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zSeasonControllerListResponse = zGetDefault;

export const zSeasonControllerCreateData = z.object({
    body: z.object({
        name: z.string().min(1),
        startsAt: z.string(),
        endsAt: z.optional(z.string())
    }),
    path: z.object({
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zSeasonControllerCreateResponse = zSeasonSchema;

export const zSeasonControllerGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        seasonId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zSeasonControllerGetResponse = zSeasonSchema;

export const zSeasonControllerUpdateData = z.object({
    body: z.object({
        name: z.optional(z.string().min(1)),
        startsAt: z.optional(z.string()),
        endsAt: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        status: z.optional(z.enum(['active', 'closed']))
    }),
    path: z.object({
        seasonId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zSeasonControllerUpdateResponse = zSeasonSchema;

export const zMatchControllerListData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.object({
        seasonId: z.string()
    })
});

/**
 * Successful response
 */
export const zMatchControllerListResponse = zGetDefault;

export const zMatchControllerCreateData = z.object({
    body: z.object({
        seasonId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        title: z.string().min(1),
        startsAt: z.string(),
        location: z.optional(z.string()),
        maxCapacity: z.int().gt(0).lte(9007199254740991),
        reminderOffsetsHours: z.optional(z.array(z.int().gt(0).lte(9007199254740991))),
        recurrence: z.optional(z.object({
            frequency: z.enum([
                'weekly',
                'monthly',
                'monthly_nth_weekday',
                'custom'
            ]),
            rrule: z.optional(z.string()),
            endsAt: z.optional(z.string()),
            occurrenceCount: z.optional(z.int().gt(0).lte(52))
        }))
    }),
    path: z.object({
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerCreateResponse = zPostDefault;

export const zMatchControllerGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerGetResponse = zMatchSchema;

export const zMatchControllerUpdateData = z.object({
    body: z.object({
        title: z.optional(z.string().min(1)),
        startsAt: z.optional(z.string()),
        location: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        maxCapacity: z.optional(z.int().gt(0).lte(9007199254740991)),
        blueScore: z.optional(z.union([
            z.int().gte(0).lte(9007199254740991),
            z.null()
        ])),
        redScore: z.optional(z.union([
            z.int().gte(0).lte(9007199254740991),
            z.null()
        ])),
        reminderOffsetsHours: z.optional(z.union([
            z.array(z.int().gt(0).lte(9007199254740991)),
            z.null()
        ]))
    }),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerUpdateResponse = zMatchSchema;

export const zMatchControllerCancelData = z.object({
    body: z.object({
        reason: z.optional(z.string())
    }),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerCancelResponse = zMatchSchema;

export const zMatchControllerMarkPlayedData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerMarkPlayedResponse = zMatchSchema;

export const zMatchControllerListAttendancesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerListAttendancesResponse = zGetMatchIdAttendances;

export const zMatchControllerRespondData = z.object({
    body: z.object({
        status: z.enum(['present', 'absent'])
    }),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerRespondResponse = zAttendanceSchema;

export const zMatchControllerSetAttendanceData = z.object({
    body: z.object({
        status: z.enum([
            'present',
            'absent',
            'pending'
        ])
    }),
    path: z.object({
        userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerSetAttendanceResponse = zAttendanceSchema;

export const zMatchControllerListLineupsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerListLineupsResponse = zGetMatchIdLineups;

export const zMatchControllerSetLineupData = z.object({
    body: z.object({
        assignments: z.array(z.object({
            userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            team: z.enum(['blue', 'red'])
        }))
    }),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerSetLineupResponse = zPutMatchIdLineups;

export const zMatchControllerSetPlayerTeamData = z.object({
    body: z.object({
        team: z.union([
            z.enum(['blue', 'red']),
            z.null()
        ])
    }),
    path: z.object({
        userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zMatchControllerSetPlayerTeamResponse = zPutMatchIdLineupsUserId;

export const zNotificationControllerGetPreferencesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zNotificationControllerGetPreferencesResponse = zNotificationPreferenceSchema;

export const zNotificationControllerUpdatePreferencesData = z.object({
    body: z.object({
        emailEnabled: z.optional(z.boolean()),
        pushEnabled: z.optional(z.boolean()),
        notifyNewMatch: z.optional(z.boolean()),
        notifyRsvpReminder: z.optional(z.boolean()),
        notifyMatchCancelled: z.optional(z.boolean()),
        notifyChatMention: z.optional(z.boolean()),
        notifyAllChatMessages: z.optional(z.boolean())
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zNotificationControllerUpdatePreferencesResponse = zNotificationPreferenceSchema;

export const zNotificationControllerRegisterDeviceData = z.object({
    body: z.object({
        token: z.string().min(1),
        platform: z.enum([
            'ios',
            'android',
            'web'
        ])
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zStatsControllerListMatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zStatsControllerListMatchResponse = zGetMatchesMatchIdStats;

export const zStatsControllerUpsertData = z.object({
    body: z.object({
        stats: z.array(z.object({
            userId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            goals: z.int().gte(0).lte(9007199254740991),
            assists: z.int().gte(0).lte(9007199254740991)
        }))
    }),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zStatsControllerUpsertResponse = zPutMatchesMatchIdStats;

export const zStatsControllerSeasonStatsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        seasonId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zStatsControllerSeasonStatsResponse = zGetSeasonsSeasonIdStats;

export const zStatsControllerHomeStatsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zStatsControllerHomeStatsResponse = zSeasonHomeStatsSchema;

export const zChatControllerListData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zChatControllerListResponse = zGetDefault;

export const zChatControllerPostData = z.object({
    body: z.object({
        body: z.string().min(1).max(4000),
        mentionedUserIds: z.optional(z.array(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)))
    }),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zChatControllerPostResponse = zMatchMessageSchema;

export const zPaymentControllerGetCostData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zPaymentControllerGetCostResponse = zMatchCostSchema;

export const zPaymentControllerUpsertCostData = z.object({
    body: z.object({
        pitchCostCents: z.int().gte(0).lte(9007199254740991),
        extrasCostCents: z.int().gte(0).lte(9007199254740991).default(0)
    }),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zPaymentControllerUpsertCostResponse = zMatchCostSchema;

export const zPaymentControllerListFeesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        matchId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zPaymentControllerListFeesResponse = zGetMatchesMatchIdFees;

export const zPaymentControllerUpdateFeeData = z.object({
    body: z.object({
        status: z.enum([
            'owed',
            'paid',
            'waived'
        ])
    }),
    path: z.object({
        feeId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zPaymentControllerUpdateFeeResponse = zSessionFeeSchema;

export const zPaymentControllerGetPaymentLinkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zPaymentControllerGetPaymentLinkResponse = zClubPaymentLinkSchema;

export const zPaymentControllerSetPaymentLinkData = z.object({
    body: z.object({
        paymentLink: z.optional(z.union([
            z.url(),
            z.null()
        ]))
    }),
    path: z.object({
        organizationId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zPaymentControllerSetPaymentLinkResponse = zClubPaymentLinkSchema;
